public/html-stimuli/mvnv-study/js/generateTwitterGraph.js, public/html-stimuli/revisit-communicate.js, src/controllers/IframeController.tsx, src/controllers/StimulusController.tsx, src/controllers/TrainingController.tsx
Closes #79 
Passes parameters of a trial from the config to the iframe data.
Iframe Stimuli can register a function to receive the message 
```js
Revisit.onDataReceive(function(stimulusData) {
// do something with the data to create an stimuli
console.log(stimulusData);
});
```
TODOs:
=> 79 pass config parameters to iframe stimuli

public/html-stimuli/mvnv-study/index.html, public/html-stimuli/stimuli-d3-interaction/bar-chart-interaction.html
Use relative path inside public folder; Fix path issue on build
=> Use relative path inside public folder

src/components/response/ResponseBlock.tsx
Closes #74 
Fixes the logic for the check answer button by making it not depend on the next button logic.
No
=> Fix check answer in practice

public/configs/config-image-demo.hjson
=> Move next button in image demo to sidebar

public/configs/config-cleveland.hjson, public/configs/config-html-demo.hjson, public/configs/config-html-input.hjson, public/configs/config-image-demo.hjson, public/configs/global.hjson, public/html-demo/bar-chart.html, public/html-input/bar-chart-interaction.html
No
Making changes towards explaining what is going on in reVISit - improving titles, other text, etc. 
Some simplification in the html inputs. 
TODOs:
=> Config improvements

public/configs/config-cleveland.hjson, public/configs/config-html-MVNV.hjson, public/html-input/bar-chart-interaction.html, public/mvnv/js/loadTasks.js, src/components/response/IframeInput.tsx, src/components/response/LikertInput.tsx, src/components/response/RadioInput.tsx, src/components/response/ResponseBlock.tsx, src/components/response/ResponseSwitcher.tsx, src/controllers/IframeController.tsx, src/parser/types.ts, src/store/flags.ts, src/store/index.ts
Closes #118 #100 
Input bug fix and new features
- add left label and right label to radio and Likert input
- Iframe input bug fixing 
- Fix bugs on practice check answer button in CM experiment
=> Input bug fix

src/firebase/init.ts
Fixes the bug where switching studies without page refresh caused Firestore error.  Firestore likes to remain a singleton, and since JS objects are recreated, directly passing an inline options object caused an error. Fixed this by moving opts to a variable and pass that instead.
=> Fixed firestore bug with changing refs for opts

public/configs/config-cleveland.hjson, public/configs/config-html-MVNV.hjson, public/configs/config-html-demo.hjson, public/configs/config-html-input.hjson, public/configs/config-image-demo.hjson, public/configs/config-survey-demo.hjson, src/components/interface/AppAside.tsx, src/parser/types.ts
Closes #103 #114 #95
- Fix bugs on survey demo
- Add meta to our demos, now meta data can be displayed in admin panel along with  ID and description
=> Config fix

public/mvnv/training/mvnv-training.html
=> Add description to mvnv training component

src/components/ConfigSwitcher.tsx
Closes #132 
Use previously exported PREFIX
=> Fix Prefix import

src/components/Shell.tsx, src/components/interface/AppHeader.tsx, src/storage/downloadTidy.ts
- Updated load session message
- Fixed error on missing values
- Added refresh on clear cache
=> Minor fixes

public/cleveland/config-cleveland.hjson, public/cleveland/introduction.md, public/configs/config-reference.hjson, public/configs/global.hjson, public/demo/config-demo.hjson, public/html-demo/config-html-demo.hjson, public/html-demo/introduction.md, public/html-input/config-html-input.hjson, public/html-input/introduction.md, public/image-demo/config-image-demo.hjson, public/image-demo/introduction.md, public/mvnv/config-html-MVNV.hjson, public/mvnv/introduction.md, public/survey-demo/config-survey-demo.hjson, public/survey-demo/introduction.md, src/components/Shell.tsx, src/components/interface/AppAside.tsx, src/components/interface/AppNavBar.tsx, src/components/response/ResponseBlock.tsx
Closes #70
Closes #83 
Closes #84
Closes #126
This cleans up the configs and adds an introduction markdown to each experiment.
Example response block:
No
=> Config clean up

.github/workflows/playwright.yml, .gitignore, package.json, playwright.config.ts, src/components/response/IframeInput.tsx, src/components/response/ResponseBlock.tsx, src/components/response/ResponseSwitcher.tsx, src/components/stimuli/inputcomponents/utils.ts, src/controllers/ComponentController.tsx, src/controllers/IframeController.tsx, src/store/flags.ts, tests/cleveland.spec.ts, tests/click-accuracy-test.spec.ts, tests/html-demo.spec.ts, tests/html-input.spec.ts, tests/image-demo.spec.ts, tests/mvnv.spec.ts, tests/survey-demo.spec.ts, tests/vlat.spec.ts, yarn.lock
No
This adds e2e testing for our example configuration files. It ensures that the default examples work as expected on each PR.
These tests already helped me find a bug in how iframe answers were recorded. I've updated that code and made the fix in this branch.
N/A
TODOs:
=> Add testing of our default configs

src/components/interface/AppHeader.tsx
Hide the menu that displays admin mode in production for running the study
=> Hide menu in production environment

src/components/interface/AppAside.tsx, src/components/interface/AppNavBar.tsx, src/components/interface/StepsPanel.tsx
1. Fixes admin mode sidebar that prevented users to scroll through a long list of tasks
2. Fix for left sidebar with task and the responses
=> Fix admin mode sidebar and task sidebar scroll issues

src/components/response/ResponseSwitcher.tsx, src/components/stimuli/inputcomponents/utils.ts
Initial value is set while generating the fields. Previously, the values were not updated to the store.
=> Set param captured value while generating fields

src/components/interface/AppHeader.tsx
Admin panel will show if admin=t appears in query params in prod mode.
=> use query parameter to control if show admin panel

src/components/response/ResponseBlock.tsx, src/storage/downloadTidy.ts, src/store/flags.ts, src/store/store.ts
- fix tidy data download bug in admin panel
- fix redundant answers problem
=> Tidy data 

public/VLAT-mini-randomized/config-VLAT-mini-randomized.hjson, src/parser/StudyConfigSchema.json, src/parser/types.ts, src/storage/downloadTidy.ts
- Add correct answer to BaseResponse; updated vlat mini config with correct answer
- Refactor json to csv converter: fixes quotes; Updated csv with correct answer and instruction
=> Fix tidy download

public/brush-interactions/config.hjson, public/brush-interactions/consent.md, public/brush-interactions/data/cars.csv, public/brush-interactions/introduction.md, src/components/response/RadioInput.tsx, src/components/stimuli/brush-interactions/Bar.tsx, src/components/stimuli/brush-interactions/Scatter.tsx, src/components/stimuli/brush-interactions/XAxisBar.tsx
=> Brush study fixes

src/storage/downloadTidy.ts
Merge each component's config with base component's config before tidy download.
=> Merge trial component with base component config before tidy download

src/components/response/ResponseBlock.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts
Closes #212 
Ability to hide response fields. These fields may be autofilled from the stimuli component programmatically.
```
...
response: [
{
id: html-response
prompt: "Answer:"
required: true
location: sidebar
type: numerical
placeholder: 0-7
min: 0
max: 7
hidden: true
}
]
```
=> Add ability to hide response fields

src/components/stimuli/brush-interactions/BrushPlot.tsx
=> changing to relative

src/components/response/ResponseSwitcher.tsx, src/utils/sanitizeStringForUrl.ts, tests/vlat.spec.ts
No
Hotfix for some small bugs described in the title
N/A
No
=> Fix issue with url capitalization and with paramCapture being disabled

src/components/Shell.tsx, src/components/StudyEnd.tsx, src/components/response/ResponseSwitcher.tsx, src/public/brush-interactions/Scatter.tsx, src/public/click-accuracy-test/ClickAccuracyTest.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts
Small PR which stores the provenance data in firebase in the storage instead of in the database to avoid size restrictions
=> Moving provenance data to storage

src/components/StepRenderer.tsx, src/components/StudyEnd.tsx, src/components/interface/AlertModal.tsx, src/controllers/ComponentController.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/initialize.ts, src/store/store.tsx, src/store/types.ts, src/utils/disableBrowserBack.tsx
Closes #120 (See TODOs)
Closes #210 
This adds an alert modal to notify users of issues. The modal takes in a message and displays that to the user, which I use to show a message when the user navigates and when adblockers are detected.
TODOs:
=> Add an alert modal to notify users when using browser back button and when adblocker breaks the storageEngine connection

public/click-accuracy-test/click-accuracy-test.hjson, public/html-input/config-html-input.hjson, public/image-demo/config-image-demo.hjson, src/components/DownloadTidy.tsx, src/components/interface/AppNavBar.tsx, src/controllers/ComponentController.tsx, src/parser/GlobalConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/parser.ts, src/parser/types.ts
No
Depends #232 
This adds much better property documentation for each property in the config.
TODOs:
=> Better documentation

.env, src/storage/engines/FirebaseStorageEngine.ts
Move recaptcha site key to env
TODOs:
=> Recaptcha site key

src/components/ReactMarkdownWrapper.tsx, src/components/response/CheckBoxInput.tsx, src/components/response/DropdownInput.tsx, src/components/response/IframeInput.tsx, src/components/response/NumericInput.tsx, src/components/response/RadioInput.tsx, src/components/response/SliderInput.tsx, src/components/response/StringInput.tsx, src/components/response/TextAreaInput.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts
Closes #188 
Closes #189
Closes #205 
This fixes some issues with the form elements:
1) The slider was missing a required *
2) The checkboxes were too small
3) We didn't allow markdown in the prompts, meaning it was impossible to embed images, link, etc.
Consistency:
`"prompt": "Dropdown [**example**](https://google.com)",`
TODOs:
=> Fix up issues with the form inputs

src/utils/handleRandomSequences.tsx
Fixes the order problem we discussed by flipping the slice and the flatten.
=> fixing order problem

src/parser/StudyConfigSchema.json, src/parser/types.ts, src/utils/handleRandomSequences.tsx
=> Don't allow the first component in a block to be a randomized interruption

public/html-input/bar-chart-interaction.html, public/html-input/config-html-input.json, tests/html-input.spec.ts
-
There was an example of passing data from HTML to reVISit, but there was no example of how to get the data (config parameters) from revisit to the html files.
-
-
=> Update example of data passing between reVISit and HTML

src/parser/types.ts
No
Updates some documentation for the types. Specifically for StudyConfig, UIConfig, and StudyMetadata.
Reading over these docs updates would be very helpful.
=> Added more docs for StudyConfig, UIConfig, and StudyMetadata

src/components/ConfigSwitcher.tsx
Closes #310 
Fixing small author space problem
=> fixing author space

src/components/interface/AppHeader.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts
Closes #305 
When the config is updated, the app will switch to new user and reload the page.
Unless the sequence array is changed, the user will be in the same stimuli.
This only applies to dev mode.
TODOs:
=> Switch to new participant when config is updated

src/Study404.tsx, src/Trial404.tsx, src/components/ConfigSwitcher.tsx, src/components/Shell.tsx, src/controllers/ComponentController.tsx
Closes #306
Adding a 404 page for the wrong study ID and wrong trial ID in URL
=> 404 page for trial and study

src/components/Shell.tsx, src/components/interface/AppHeader.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/storage/types.ts, src/store/store.tsx, src/store/types.ts
Closes #307 
Adds basic metadata to a participant, specifically 
{
userAgent: string;
resolution: Screen;
language: string;
ip: string | null;
}
=> Adding basic browser metadata

src/analysis/dashboard/SummaryPanel.tsx, src/components/Shell.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/types.ts
No
This fixes a bug with the analysis dashboard and with the data. Now that we're allowing skipping, we need to record when a participant has finished the study. I'm adding a `completed` variable to the participant data that is updated when we `verifyAnswers`.
N/A
No
=> Add a completed variable to the participant data to find when people finish studies (req. for skip logic changes)

src/Login.tsx, src/ProtectedRoute.tsx, src/analysis/dashboard/SummaryBlock.tsx, src/components/Shell.tsx, src/store/hooks/useAuth.tsx
No
Fixes a bug with 2 different loader sizes. I standardized the usage of the loading overlay and fixed a loader with a custom size.
N/A
No
=> Fix loading overlay usage

.github/workflows/release.yaml
=> v1.0.0-beta2

.github/workflows/release.yaml
Add tag pushing so the tags make it up to GitHub
=> v1.0.0-beta4

src/components/Shell.tsx, src/components/interface/AppHeader.tsx, src/store/store.tsx
No
Logging in as an admin shows the ... menu, and opens the StudyBrowser by default
=> adding sidebar if admin, opening by default

src/storage/engines/LocalStorageEngine.ts
Fix the localStorage data fetch bug, which causes crash on the analysis dashboard
=> bug fix - remove config hash in participants data

src/storage/types.ts, src/store/types.ts, typedocReadMe.md
Updates study repo to have correct relative links for typedoc.
=> Fixed types to point using completely relative paths in docusaurus

.github/workflows/release.yaml, src/parser/types.ts
Closes #284 
Closes #282 
Fixes bugs in the sed command for publishing docs changes, adds documentation for questionnaire and markdown components
N/A
No
=> Fix some more bugs with sed, add some documentation for questionnaire and markdown components

src/analysis/stats/TableView.tsx, src/components/DownloadTidy.tsx
No
Fix up the couple of issues brought up in reviewing this code today
No
=> Quick table fixes

src/analysis/stats/TableView.tsx, src/components/DownloadTidy.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/store/hooks/useNextStep.ts, src/store/hooks/useStoredAnswer.ts, src/store/store.tsx
Closes #266
Closes #253 
This moves the participant data to firebase storage
N/A
TODOs:
=> Store all data (participants, configs) in firebase storage

src/analysis/AnalysisInterface.tsx, src/analysis/components/interface/ParticipantStatusBadges.tsx, src/analysis/dashboard/SummaryPanel.tsx, src/analysis/table/TableView.tsx
=> Participant badge clean up, table scroll fix, and coming soon for unused analysis platform tabs

.eslintrc.json, index.html, public/demo-survey/config.json, public/test-skip-logic/config.json, src/GlobalConfigParser.tsx, src/analysis/dashboard/SummaryBlock.tsx, src/analysis/dashboard/SummaryPanel.tsx, src/analysis/table/TableView.tsx, src/components/downloader/DownloadTidy.tsx, src/components/interface/AlertModal.tsx, src/components/interface/AppAside.tsx, src/components/response/IframeInput.tsx, src/components/response/ResponseBlock.tsx, src/components/response/utils.ts, src/parser/StudyConfigSchema.json, src/parser/types.ts, src/storage/engines/LocalStorageEngine.ts, src/store/hooks/useNextStep.ts, src/utils/PageTitle.tsx, tests/demo-survey.spec.ts
See linked issues
Fixes up multiple issues. See commit messages for more information.
=> Multiple fixes for some rough edges

src/components/settings/GlobalSettings.tsx
Closes #440
If trying to enable authentication without Google Provider enabled, an error message will instead pop up to tell the user to consult the documentation. This works if you were to also close Google's "choose account" window (It will first show as just loading in the page until after about 5-10 seconds, it will show the error). Note that the documentation link goes directly to the authentication documentation.
=> 440 auth disabling

public/demo-click-accuracy-test/config.json, src/public/demo-click-accuracy-test/assets/ClickAccuracyTest.tsx, tests/demo-click-accuracy-test.spec.ts
- Update config file for click accuracy test, make it use base component, prepared for demo 1 in the tutorial
- Fixed the bug that the test did not pick the original speed in the config file.
=> Update click accuracy demo

public/demo-survey/assets/introduction.md, public/demo-survey/config.json, src/components/response/MatrixInput.tsx, tests/demo-survey.spec.ts, typedocReadMe.md
No
* Added the matrix to the example form study
* Added secondary labels to all questions 
* Improved documentation for form elements
=> Form improvements

public/example-brush-interactions/config.json, public/libraries/color-blindness/config.json, src/analysis/individualStudy/replay/AllTasksTimeline.tsx, src/components/interface/StepsPanel.tsx, src/components/response/ResponseBlock.tsx, src/components/response/ResponseSwitcher.tsx, src/components/response/utils.ts, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts, src/store/types.ts
Closes #556 
Closes #553 
Adds ID to steps panel and adds an I don't know button
No
=> Add ID to steps panel and adds an I don't know button

src/components/audioAnalysis/WithinTaskProvenance.tsx
Add color encoding for activity in the replay timeline with a legend.
=> Replay timeline UI

public/demo-image/config.json, public/example-fairness-jnd/config.json, src/components/NextButton.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts, tests/demo-image.spec.ts
Closes #569 
Enables global go to next component on enter key
N/A
No
=> Go to next component on enter key

public/demo-vega/assets/introduction.md, public/demo-vega/config.json
No
Improving description and links for the vega study example
TODOs:
=> Vega example improvements

public/demo-survey/config.json, src/analysis/interface/AppHeader.tsx, src/components/response/CheckBoxInput.tsx, src/components/response/RadioInput.tsx, tests/demo-survey.spec.ts
Closes #580 
Closes #583 
Fixes up a couple UI issues
Other on horizontal layout radio/checkbox:
Go To Study in top right:
No
=> Re-style horizontal form elements with other, add a link back to study from analysis

public/libraries/mini-vlat/config.json
Closes #608
Fixed the typos in the mini-vlat library
No
=> fix typos in mini-vlat

public/revisitUtilities/revisit-communicate.js, src/controllers/ComponentController.tsx, src/controllers/IframeController.tsx, src/controllers/ReactComponentController.tsx, src/public/example-brush-interactions/assets/BrushPlot.tsx, src/public/tutorial/assets/BrushPlotWrapper.tsx, src/public/tutorial/assets/ReactExample.tsx, src/public/tutorial/assets/_answers/ReactExample.tsx, src/store/types.ts
Passing the answers object to react components, as well as passing both answers and provenance components to iframes via messaging.
=> Passing provenance/answers to website, answers to react

src/GlobalConfigParser.tsx, src/analysis/individualStudy/StudyAnalysisTabs.tsx, src/analysis/individualStudy/stats/InfoPanel.tsx, src/components/audioAnalysis/AudioProvenanceVis.tsx, src/components/interface/StepsPanel.tsx, src/controllers/IframeController.tsx, src/controllers/ReactComponentController.tsx, src/public/tutorial/assets/BrushPlotWrapper.tsx, src/routes/utils.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/store/store.tsx, src/store/types.ts
Closes #654
Closes #655
Closes #626 
Closes #648 
Don't text wrap on long component names. Add component name, correct answer, response to hover card.
Also fixes issue with dynamic blocks in the study browser.
TODOs:
=> Study browser improvements

src/components/response/MatrixInput.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts
Closes #522
Matrix rows can be fixed or random (questionOrder: 'fixed', 'random')
TODOs:
=> Randomize row in Matrix (fixed, random)

src/components/StepRenderer.tsx, src/components/interface/AppAside.tsx, src/components/interface/AppHeader.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts
Closes #673
Sometimes user might want to turn off the title or title bar. If showTitle = false, the title will be hidden in the study. 
If showTitleBar is false, the entire title bar will be hidden. If the user closes study browser, user can click on Study Browser to open it again.
showTitle = false
showTitle = true or undefined
showTitleBar = false
toggle study browser (shows up only when showTitleBar = false)
https://github.com/user-attachments/assets/2de7f5d1-201d-4666-904c-e7012992d1ab
showTitleBar = true or undefined
TODOs:
- None
=> Turning off title and title bar

src/components/interface/AppAside.tsx
Fix typo in study browser open
Updated Tooltip text to "The study browser cannot be closed in replay mode"
TODOs:
None
=> Fix typo in study browser open

src/analysis/individualStudy/StudyAnalysisTabs.tsx, src/analysis/individualStudy/management/DataManagementAccordionItem.tsx, src/analysis/individualStudy/management/ManageAccordion.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/SupabaseStorageEngine.ts, src/storage/engines/types.ts, src/storage/tests/highLevel.spec.ts, src/storage/tests/primitives.spec.ts
Closes #767
Moves snapshotting up to the `StorageEngine` class and provides implementations for each storage engine. 
N/A
TODOs:
=> Enable snapshots on all storage engines

public/libraries/nasa-tlx/config.json, public/library-nasa-tlx/assets/nasa-tlx.md, public/library-nasa-tlx/config.json
No
- Added the source of load evaluation procedure to the NASA TLX library
- Updated the library and the example study of NASA TLX
No
=> Update nasa tlx

public/demo-vega/config.json, src/controllers/VegaController.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts
Closes #760
This adds a flag to remove the Vega actions (screenshot, download, etc.)
Pre:
Post (withActions: false):
No
=> Add configuration option to disable Vega actions

.gitignore, .vscode/settings.json, package.json, public/demo-yaml/assets/bar-chart.html, public/demo-yaml/assets/help.md, public/demo-yaml/assets/introduction.md, public/demo-yaml/config.yaml, public/global.json, src/parser/parser.ts, yarn.lock
Closes #748
This adds a YAML parser to the app and allows configs to be written and parsed from YAML. I also added a settings.json file that configures the vscode YAML parser to use the on disk schema so that the YAML can be validated and autocompleted in editor. I think this is a fine extension for now, and if we get more requests for other formats, we can re-engineer to support more.
See deployment for demo-yaml
TODOs:
=> Enable YAML configurations

src/components/StepRenderer.tsx, src/controllers/ComponentController.tsx, src/controllers/IframeController.tsx
No
Refactors the iframe sizing code to make use the whole height of the main panel
Before
After
No
=> Iframe size

package.json, src/components/ReactMarkdownWrapper.tsx, tests/demo-html.spec.ts, yarn.lock
No
Adds markdown tables using the GitHub table syntax
No
=> Add markdown tables

src/components/ReactMarkdownWrapper.tsx, src/components/response/ButtonsInput.tsx, src/components/response/CheckBoxInput.tsx, src/components/response/DropdownInput.tsx, src/components/response/InputLabel.tsx, src/components/response/MatrixInput.tsx, src/components/response/NumericInput.tsx, src/components/response/RadioInput.tsx, src/components/response/ReactiveInput.tsx, src/components/response/SliderInput.tsx, src/components/response/StringInput.tsx, src/components/response/TextAreaInput.tsx
No
Title explains the fix. The label will now not render if there is no prompt text so we don't get weird dangling required asterisks. This will need to be cleaned up in #486
N/A
No
=> Refactor input labels into one component, fix asterisk wrap, don't render if no prompt

src/components/response/ResponseBlock.tsx
Closes #794
Add disable check answer button
Disabled when
- Correct answer has been selected
- Allowed attempts have been used up
https://github.com/user-attachments/assets/3d6a44db-3618-4bee-9de6-cd140f20ab48
https://github.com/user-attachments/assets/28ecb95c-71d3-44ee-827d-46fd6c8d3ea7
TODOs:
No
=> Add disable check answer button

src/analysis/individualStudy/replay/AllTasksTimeline.tsx, src/analysis/individualStudy/stats/ResponseVisualization.tsx, src/analysis/individualStudy/summary/utils.tsx, src/analysis/individualStudy/table/TableView.tsx, src/components/interface/StepsPanel.tsx, src/store/hooks/useNextStep.ts, src/utils/correctAnswer.ts
Closes #752
Fix multi select answer marked as incorrect in sidebar
Before
After
TODOs:
=> Fix multi select answer marked as incorrect

public/example-brush-interactions/assets/tutorial.md, src/components/ReactMarkdownWrapper.tsx
Closes #815 
Fix where the last image in Markdown isn’t being rendered
Before
After
No
=> Fix last image not rendering in Markdown

public/libraries/nasa-tlx/config.json
Closes #836 
- Remove the repeated questions in the sources of load questionnaire in the NASA TLX libary
- Make the option order random
No
=> Fix nasa tlx library bug

src/analysis/individualStudy/StudyAnalysisTabs.tsx, src/analysis/individualStudy/stats/ResponseVisualization.tsx
Closes #830 
Closes #831 
Fix scrolling problem in trial stats & manage page
Add trial stats & icons for textOnly, matrix radio, matrix checkbox, and buttons
Trial stats
Manage
https://github.com/user-attachments/assets/00694e05-4f81-425b-88f6-b46e91b62063
Before
After
Before
After
https://github.com/user-attachments/assets/996321a5-6c3d-4d91-9225-62d41de99adb
Before
After
https://github.com/user-attachments/assets/979008df-b1c4-461c-934d-f816070a8e64
Before
After
TODOs:
=> Fix scrolling trial stats

.github/workflows/deploy_website.yaml
=> Add dev branch preview on push to dev and simplify workflow into 3 build jobs
