revisit-studies/study

public/configs/config-html-MVNV.hjson, public/html-stimuli/mvnv-study/training/mvnv-training.html, vite.config.ts
No
The training wasn't loading on prod because of an absolute import that was broken. By moving some files around, I can do a relative import, which should fix it.
N/A
No
=> Move training html so we can import video relatively

src/components/interface/AppNavBar.tsx
Closes #115 
All the props passed to ResponseBlock could be same for different stimuli preventing re-rendering of the component.
So, adding key fixes the issue of not re-rendering when stimuli is updated.
=> Add trialId as key in response block

src/components/interface/AppAside.tsx
Depends #148 
Closes #95 
This PR makes the admin panel use `task.id` instead of `task.instruction`.
No
=> Use task.id as task title in the admin panel

.github/workflows/deploy.yaml, .gitignore, package.json, src/parser/types.ts, typedoc.json, yarn.lock
Closes #153 
This PR adds the ability to automatically generate type documentation from the TS parser files. I'm using typedoc with some plugins (markdown and frontmatter) — this lets us generate files that Jekyll can parse. This then goes into the build for revisit.dev.
I'm attempting to trigger the build from all pushes to main here. We'll have to see if that works :)
N/A
TODOs:
=> Add typedoc generation

public/VLAT/config-VLAT.hjson, src/components/NextButton.tsx, src/components/response/ResponseSwitcher.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts
Parameters such as prolific id will to be automatically populated in the forms.
If there is such parameter, the field is disabled.
**Example config**
```json
{
"response": [
{
"id": "prolificId",
"prompt": "Please enter your Prolific ID",
"required": true,
"location": "belowStimulus",
"type": "shortText",
"placeholder": "Prolific ID",
"paramCapture": "PROLIFIC_ID"
}
]
}
```
=> Add ability to capture url parameters

.env, package.json, src/components/DownloadPanel.tsx, src/components/DownloadTidy.tsx, src/components/GlobalInitializer.tsx, src/components/StudyEnd.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/storage/initialize.ts
Closes #195 
This adds a screen before the end of study screen that shows the user that the answers are uploading. I decided to add a method to loop through the sequence and verify that they were answers for each step. This works well, since even steps without responses save an empty object in the answers, but shows the spinner forever if you jump to the end as an admin
No
=> Add an end of study uploading notification

public/html-demo/config-html-demo.hjson, src/components/DownloadTidy.tsx, src/components/StepRenderer.tsx, src/controllers/ComponentController.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts, src/storage/engines/FirebaseStorageEngine.ts, src/store/hooks/useNextStep.ts, src/store/store.tsx, src/store/types.ts
No
This tracks all mouse, keypresses, scroll, change tab, etc. events so that they can be rehydrated later. The interval can be modified in the `studyConfig.uiConfig` using `windowEventDebounceTime` which takes a time in ms to debounce by. For example, `100` would give events 10 times per second and `200` would be 5 times per second.
The way that the windowEvents are saved is similar to the provenance. That is, stored as an array on the answers for a particular step, so it can be retrieved in a similar way. Additionally, this makes the logic to save and load the events the same as the provenanceGraph. As such, I've simplified the logic for these two properties in the firebaseStorageEngine to remove as much code duplication as possible
TODOs:
=> Track all events for later rehydration

src/components/Shell.tsx, src/components/interface/AppHeader.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/storage/engines/utils.ts, src/storage/types.ts
Closes #236 
This saves the config version in the participant data so that we can figure out the config version a participant saw. This is useful if the config changes from pilot to study for example.
Currently, there is not a great way to download the configs, but we should add that in a follow up. Right now, this will work for our use case poking around in the database.
N/A
TODOs:
=> Add config hash to ParticipantData allow multiple config versions

src/components/DownloadPanel.tsx, src/components/interface/AppAside.tsx
Closes #143
This fixes the issues with auto download. Now, the admin panel is rendered if auto download is selected and we're at study end. Also, the auto download functionality was broken, so I fixed it up using a `useCallback` hook.
N/A
No
=> Fix the issues with the auto download functionality

.github/workflows/playwright.yml, src/parser/StudyConfigSchema.json, src/parser/types.ts, src/storage/engines/FirebaseStorageEngine.ts, src/utils/handleRandomSequences.tsx
Closes #176 
Closes #250 
This fixes the issues with the sequence array:
1. The sequence array could be too large. I fixed this by using storage, which has no real size limitation.
2. Race conditions when pulling a sequence. I fixed this in 2 ways. The first fix is to not modify the sequence array, thus we can just get an index and take the sequence at that index as our sequence. Second, I made the firebase database track a timestamp of a participants intent to get a sequence, which can then be used to find the order in which people state their intent. We can use these 2 fixes together to avoid any race conditions.
N/A
TODOs:
=> Fix sequence array size limitations and data races

src/parser/types.ts, src/storage/types.ts, src/store/types.ts
Adds ParticipantData documentation and the documentation for relevant sub types. 
Closes #281 
For this, decided to export the ParticipantDat, StoredAnswer, and Sequence interfaces in the parser/types.ts file so we could still have just one entry point for the tyepdoc.json file. Added the relevant eslint commands to disable errors on the circular imports that were caused.
=> Participant data docs

src/utils/handleRandomSequences.tsx, tests/randomization-test.spec.ts
No
There was an issue with nested latin squares where we would pop a randomization and not use it. This led to imbalanced randomization, but was easily fixed by modifying the sequence generation logic. We needed to randomize first, prune using numSteps, then recurse.
I updated the test to check that the behavior is as we expect.
N/A
No
=> Fix bug with nested latinSquares

src/store/hooks/useAuth.tsx
Changed the authentication system to be disabled by default (only enabled when firestore variable is set and is set to true).
TODOs:
=> Changed authentication to be disabled by default.

public/demo-html/config.json, src/GlobalConfigParser.tsx, src/components/ConfigSwitcher.tsx, src/components/ErrorLoadingConfig.tsx, src/components/Shell.tsx, src/parser/parser.ts, src/utils/fetchConfig.ts
Closes #178 
This adds feedback for configuration errors to the main application in the config switcher, and the study itself.
No
=> Add error reporting for studies with configuration file errors

src/analysis/dashboard/SummaryBlock.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts
Analysis dashboard not available with Firebase storage
Analysis dashboard was pulling in data for each study by initializing a storage engine for each one. We've changed this to pull participant data by the studyId that was given. Prevents issues trying to initialize too many firebase applications at once.
=> Fixing analysis dashboard. Pulls participant data all at once 

.env, playwright.config.ts, src/components/interface/AppAside.tsx, src/components/interface/AppHeader.tsx, src/storage/initialize.ts, src/store/store.tsx, src/store/types.ts, src/utils/useDisableBrowserBack.tsx, tests/test-randomization.spec.ts, tests/test-skip-logic.spec.ts
Closes #316 
Closes #317 
Closes #318
Adds a public mode, set via the env variable 'VITE_REVISIT_MODE', checking if it is 'public'. 
If it is, does a few things 
- Sets the storage engine to localStorage, so that nothing is tracked
- Adds a banner telling people we are in public mode, and they arent being tracked
- Gives access to the study browser dropdown/sidebar, and opens the study browser by default.
=> Adding public mode

public/demo-html-input/config.json, src/components/interface/AppHeader.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts
Closes #339 
Config sequence changes were not reflected in the interface.
This PR clears the sequence array and current participant id when config is changed (for both localStorage and firebase).
Clearing the sequence array forces sequence array to be repopulated.
Clearing current participant id forces new participant id to be set.
x
x
=> Clear sequence array and current participant when config is changed 

src/Login.tsx, src/analysis/AnalysisInterface.tsx, src/analysis/dashboard/SummaryPanel.tsx, src/analysis/management/DataManagementBoard.tsx, src/analysis/stats/TableView.tsx, src/components/DownloadTidy.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/store/hooks/useNextStep.ts, src/store/hooks/useStoredAnswer.ts, src/store/store.tsx
Closes https://github.com/revisit-studies/study/issues/266
Closes https://github.com/revisit-studies/study/issues/253
Closes #334 
Closes #386 
Closes #384 
This allows for better data management when using Firebase. What created an additional tab in the individual analysis views which is meant for data management. The functionality is as follows:
1. A user can "archive" a dataset. When you archive the data, it is copied to a separate directory in storage labeled exactly the same as the study with an additional "-archive-YYYYMMDDhhmmss" suffix. 
2. A user can "archive and delete" a dataset. This will not only archive the data, but will clear out the current study data as well. We can think of this as a "reset" and we can think of just archiving as a "snapshot".
3. A user can "restore" any …
=> Clear database feature

src/components/interface/AppAside.tsx, src/components/interface/AppHeader.tsx, src/components/interface/AppNavBar.tsx, src/components/interface/StepsPanel.tsx, src/components/response/ResponseBlock.tsx, src/components/response/utils.ts, src/controllers/ComponentController.tsx, src/controllers/IframeController.tsx, src/controllers/ReactComponentController.tsx, src/public/demo-fairness-jnd/assets/FairnessJND.tsx, src/routes/utils.tsx, src/store/hooks/useNextStep.ts, src/store/hooks/useStoredAnswer.ts, src/store/store.tsx
Closes #319 
This adds the ability for a reviewer to navigate to any component in the study config order, even if it is not included in a participant's sequence.
Participant view
Reviewer view
TODOs:
=> Enable a reviewer mode in the study browser

index.html, public/revisitAssets/cssOverrides.css, src/components/ReactMarkdownWrapper.tsx, src/components/interface/AppAside.tsx, src/components/interface/AppHeader.tsx, src/components/interface/AppNavBar.tsx, src/components/interface/StepsPanel.tsx, src/components/response/CheckBoxInput.tsx, src/components/response/DropdownInput.tsx, src/components/response/IframeInput.tsx, src/components/response/LikertInput.tsx, src/components/response/NumericInput.tsx, src/components/response/RadioInput.tsx, src/components/response/ResponseBlock.tsx, src/components/response/ResponseSwitcher.tsx, src/components/response/SliderInput.tsx, src/components/response/StringInput.tsx, src/components/response/TextAreaInput.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts, src/utils/nextParticipant.ts, tests/demo-cleveland.spec.ts, tests/demo-click-accuracy-test.spec.ts, tests/demo-html-input.spec.ts, tests/demo-html.spec.ts, tests/demo-image.spec.ts, tests/demo-mvnv.spec.ts, tests/demo-survey.spec.ts, tests/demo-vlat.spec.ts, tests/test-skip-logic.spec.ts
Closes #397 
Improves a bunch of our UI, including enumerating questions, adding secondary text to inputs, custom sidebar width, and using tabs in the study browser.
Enumerating questions:
Secondary text:
Custom sidebar width:
Tabs:
No
=> UI cleanup

src/analysis/components/interface/AppHeader.tsx, src/storage/engines/FirebaseStorageEngine.ts
Fixes issue brought up in Core. Also added navigation to the Login screen whenever clicking 'logout'.
New users were not properly having their UID added to firestore, causing the application to crash.
For the 'logout' behavior, there is no necessity to navigate to the Login screen in general, but when you're on a protected route, this will happen automatically. Thus, for consistency, I decided to make it so that clicking logout navigates you to the login no matter what.
=> Admin user fix

.env, src/GlobalConfigParser.tsx, src/ProtectedRoute.tsx, src/analysis/AnalysisInterface.tsx, src/analysis/components/interface/AppHeader.tsx, src/analysis/dashboard/GlobalSettings.tsx, src/analysis/dashboard/SummaryBlock.tsx, src/analysis/management/DataManagementAccordionItem.tsx, src/analysis/management/ManageAccordion.tsx, src/analysis/management/RevisitModesAccordionItem.tsx, src/components/Shell.tsx, src/components/StepRenderer.tsx, src/components/StudyEnd.tsx, src/components/interface/AppAside.tsx, src/components/interface/AppHeader.tsx, src/controllers/ComponentController.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/storage/initialize.ts, src/store/hooks/useNextStep.ts, src/store/store.tsx, src/utils/nextParticipant.ts, src/utils/useDisableBrowserBack.tsx, tests/test-randomization.spec.ts
Closes #407 
This adds revisit modes for dataCollectionEnabled, studyBrowser, and analysisPublic. This allows us to toggle the settings from the firebase/UI and let's the application react according for debugging, etc.
No
=> Add revisit modes in analysis interface

src/Login.tsx, src/analysis/dashboard/StudyCard.tsx, src/analysis/individualStudy/management/DataManagementAccordionItem.tsx, src/components/downloader/DownloadButtons.tsx
Closes #451 
Added download buttons to each snapshot. When clicked, the data is labeled with the snapshot name (the alternate name, so if it was renamed, it will use the renamed value).
To do this, the download buttons component needed to be adjusted to take in a list of participants data (like originally done) OR a function which fetches that data. It also takes in a couple other optional attributes for styling and file naming.
=> Adding download snapshots

public/demo-cleveland/config.json, src/components/NextButton.tsx, src/components/response/ResponseBlock.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts, tests/demo-cleveland.spec.ts, tests/test-training-feeback.spec.ts
No issue for this
Adds the ability to retry training questions up to a maximum amount where it's possible to prevent the participant from continuing using the next button.
TODOs:
=> Allow retrying training questions, disabling continuation if the answers are wrong

public/demo-VLAT-full-randomized/config.json, public/demo-VLAT-mini-randomized/config.json, public/demo-brush-interactions/config.json, public/demo-cleveland/config.json, public/demo-image/config.json, public/demo-mvnv/config.json, public/demo-survey/config.json, public/test-skip-logic/config.json, src/analysis/individualStudy/stats/AnswerPanel.tsx, src/components/response/CheckBoxInput.tsx, src/components/response/DropdownInput.tsx, src/components/response/RadioInput.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts
No
Allows a simplification of the config, by allowing the options array to be defined using lists of strings instead of list of objects, e.g.:
```
"options": [
"Bar",
"Bubble",
"Pie",
"Stacked Bar"
]
```
TODOs:
=> Add ability to define StringOption arrays as string arrays

src/analysis/dashboard/StudyCard.tsx, src/analysis/individualStudy/stats/InfoPanel.tsx, src/analysis/individualStudy/stats/ResponseVisualization.tsx, src/analysis/individualStudy/table/TableView.tsx, src/components/StudyEnd.tsx, src/components/downloader/DownloadTidy.tsx, src/components/interface/AlertModal.tsx, src/components/interface/AppAside.tsx, src/components/interface/AppHeader.tsx, src/components/interface/HelpModal.tsx, src/components/response/IframeInput.tsx, src/components/response/ResponseBlock.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/storage/types.ts, src/store/hooks/useNextStep.ts, src/store/hooks/useStoredAnswer.ts, src/store/store.tsx, src/store/types.ts, src/utils/getCleanedDuration.ts, tests/test-training-feeback.spec.ts
Closes #461 
Closes #450
Closes #216 
Added multiple features/fixes:
- Reject participants on failed training
-  With rejection reason, "failed training"
- add rejection reason
- Identifies why people were rejected (optional)
- In this refactor, added number to the button so you can see how many people will be rejected
- fix redux state getters
- Addressed a console error here
- add cleaned duration to csv export and table view
- Automatically handles the window events for visibility so that an analyst can see how long participants were looking at the tab.
No
=> Reject participants on failed training, add rejection reason, fix redux state getters, add cleaned duration to csv export and table view

public/demo-image/config.json, src/analysis/individualStudy/table/TableView.tsx, src/components/TimedOut.tsx, src/components/response/ResponseBlock.tsx, src/controllers/ComponentController.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts, src/store/hooks/useNextStep.ts, src/store/store.tsx, src/store/types.ts
Closes #449 
This pull request introduces a new feature to control the timing of the "Next" button in the response block, along with some schema updates and UI enhancements.
Adds a timer and 2 config options that either require a certain to have passed before the next button becomes available or disables the next button after a certain amount of time.
I had to modify some helpers slightly so that the participant answers would not be recorded on an incorrect answer. We still save a StoredAnswer (so we can replay provenance, etc.), but don't save any answers from the answer validator.
TODOs:
=> Add next button wait and timeout

public/test-skip-logic/config.json, src/analysis/individualStudy/table/TableView.tsx, src/components/downloader/DownloadTidy.tsx, src/controllers/ComponentController.tsx, src/storage/engines/FirebaseStorageEngine.ts, src/storage/engines/LocalStorageEngine.ts, src/storage/engines/StorageEngine.ts, src/storage/types.ts, tests/test-skip-logic.spec.ts
Closes #474
Closes #475 
Closes #485 
This pull request introduces `participantTags`. Participant tags exist to allow tagging whole participants based on some criteria. The initial, automatic tagging that I've added is to tag when a participant enters into a sequence block with an ID. This could be useful if there is branching logic, to quickly find participants that took path A vs path B.
The code changes are as follows:
- Updated `ParticipantData` interface to include `participantTags` property.
- Added methods to get, add, and remove participant tags in the storage engines.
- Updated the ComponentController to fetch the block for the current step and add it as a participant tag automatically.
- Modified the skip logic test to verify the correct handling of participant tags, ensuring …
=> Add participantTags and add sequence block tags when navigating through the sequence

src/analysis/individualStudy/table/TableView.tsx, src/components/interface/AppHeader.tsx, src/components/response/ResponseBlock.tsx, src/store/hooks/useNextStep.ts, src/store/store.tsx, src/store/types.ts
Does 3 things 
- Store any incorrect answers a participant makes during a training trial, which aren't used as the final answer. Stores them as an array of values.
- Store a click counter for the help button, to keep track of how many times someone opens the help panel. Counts both clicks of the help button directly, as well as when someone opens the panel via the feedback after getting a training trial wrong
- Makes trainingAttempts = -1 in the config work as the documentation said it did, which is giving unlimited trials and never showing the correct answer.
=> Store training incorrect answers

src/components/ConfigSwitcher.tsx, src/components/response/SliderInput.module.css, src/components/response/SliderInput.tsx, src/components/settings/GlobalSettings.tsx
No, user reported bugs
Slider labels could overflow, this should fix that with a small CSS tweak.
We want to be able to hide studies in the "your studies" tab on the main page. If the revisit mode has `analyticsInterfacePubliclyAccessible = true`, then it renders, otherwise, it does not render on the front page. Obviously if the user is an admin, it still shows.
Slider:
No
=> Fix issue with slider label alignment, hide not publicly accessible studies from "your studies" on landing page

package.json, public/demo-html/config.json, public/demo-image/config.json, public/demo-video-slider/config.json, public/demo-video/assets/help.md, public/demo-video/assets/introduction.md, public/demo-video/config.json, public/global.json, src/components/interface/HelpModal.tsx, src/controllers/ComponentController.tsx, src/controllers/ImageController.tsx, src/controllers/MarkdownController.tsx, src/controllers/VideoController.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts, src/store/store.tsx, src/store/types.ts, src/utils/getStaticAsset.ts, tests/demo-image.spec.ts, typedocReadMe.md, yarn.lock
Closes #548 
Adds a video stimulus with options to `forceCompletion` and to `showTimeline`.
To enable the `forceCompletion` flag, I had to add an additional piece to the validation object (`'stimulus'`). This is invalidated if forceCompletion is true and re-validated when the video is completed.
One additional improvement in this PR is enabling the image component to use external images. This was always my intention, but seemed to be hard coded to only work with images in the public folder.
TODOs:
=> Add video stimulus

public/demo-training/config.json, src/components/interface/HelpModal.tsx, src/components/interface/StepsPanel.tsx, src/components/response/ResponseBlock.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts
Adds a validation message for checkbox training tasks that are wrong. The message says how many out of the total are correct, though still does that if you get all 3 correct but also have extra (so the message will be 3/3, even though its wrong) which is a bit odd but couldnt think of a better way to do it. 
Also added a prop to the baseComponent which lets people override the helpPath so they can show different help pages for different components
Also made some small changes to the StepsPanel which hides and doesn't render portions of the sidebar which arent open. Only opens the portions which are active by default. This was mainly to fix problems the sidebar caused by rendering too many elements in the dom when the study is complex.
=> Checkbox validation message, unique help button

public/demo-survey/config.json, src/components/response/ButtonsInput.module.css, src/components/response/ButtonsInput.tsx, src/components/response/ResponseSwitcher.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts, tests/demo-survey.spec.ts, typedocReadMe.md
Closes #610 
Adds cursor buttons that function as a radio. They work with the left and right arrows by default, I didn't need to add any additional logic to handle that.
Unselected:
Selected:
Hydrated from answers:
TODOs:
=> Add a ButtonsInput

src/components/response/SliderInput.module.css, src/components/response/SliderInput.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts
Closes #615 
#519?
Makes the slider fill optional, so that the thumb moves without filling a bar.
`withBar: false`
No
=> Optional slider fill

src/components/interface/StepsPanel.tsx
Closes #691 
Adds participant responses to the tooltip in the study browser and reorders some of the information to show most relevant info first.
I also added a max width of 500px.
TODO:
=> Add participant responses to the tooltip in the study browser

public/demo-survey/config.json, src/components/response/ResponseBlock.tsx, src/components/response/ResponseSwitcher.tsx, src/components/response/TextOnlyInput.tsx, src/parser/LibraryConfigSchema.json, src/parser/StudyConfigSchema.json, src/parser/types.ts, tests/demo-survey.spec.ts, typedocReadMe.md
Closes #515 
Add a markdown field to responses that don't capture any user input. This can be used to define a header or other text that will be shown to the user. 
There is an optional flag for restarting the enumeration of questions.
It's all documented up for the typedoc.
Without `restartEnumeration`:
With `restartEnumeration: true`:
TODOs:
=> Add TextOnlyResponse which just renders text (optionally as a header)

src/components/ConfigSwitcher.tsx, src/components/interface/AppAside.tsx
Closes #622 
Show icons and tooltips at study broswer and study overview
Study Status: Collecting data
Study Navigator: Enabled
Analytics Interface: Accessible
Storage: Firebase
https://github.com/user-attachments/assets/5cd38347-392a-4ba1-ba77-1cdddaa6f304
Study Status: Data Collection Disabled
Study Navigator: Disabled
Analytics Interface: Not accessible
Storage: Local Storage
https://github.com/user-attachments/assets/488056de-be6b-4d97-9b22-b8ab3361f61c
Study Status: Collecting data
Analytics Interface: Accessible
Storage: Local
https://github.com/user-attachments/assets/53b4a02e-e0a7-42ab-a9ce-85fbe7c0bd4d
Study Status: Data Collection Disabled
Analytics Interface: Not accessible
Storage: Firebase
https://github.com/user-attachments/assets/47e37df1-386b-4536-80e8-a58c11524193
TODOs: …
=> Add status icons 

src/components/interface/AppAside.tsx
Closes #687 
Update the study browser button to disable when hovered, and add a tooltip
https://github.com/user-attachments/assets/9c111a92-065a-45a0-b0e5-9778c810c786
TODOs:
None
=> Add disable study browser tooltip and warning

src/components/response/CheckBoxInput.tsx, src/components/response/RadioInput.tsx
When radio/checkbox options are provided with list of strings in dynamic stimuli, the options are rendered as empty string. This was occurring because of same key attribute for each option.
=> Fix options for radio and checkbox input

public/example-VLAT-full-randomized/config.json, public/example-VLAT-mini-randomized/config.json, public/example-brush-interactions/config.json, public/test-audio/config.json, src/components/StudyEnd.tsx, src/parser/StudyConfigSchema.json, src/parser/types.ts
Closes #739 
Allow variable injection at the study end
Uses
``` ts
/** The message to display when the study ends. Supports templating with the participant ID. e.g. "Thank you for completing the study. You may click this link and return to Prolific: [Go to Prolific](https://app.prolific.com/submissions/complete?cc=StudyID&PROLIFIC_ID={PROLIFIC_ID}))" */
studyEndMsg?: string;
/** If the participant ID is passed in the URL, this is the name of the querystring parameter that is used to capture the participant ID (e.g. PROLIFIC_ID). This will allow a user to continue a study on different devices and browsers. */
urlParticipantIdParam?: string;
```
```json
"uiConfig": {
"studyEndMsg": "Thank you for completing the study. You may click this link and return to Prolific: …
```
=> Allow variable injection at the study end

src/components/interface/RecordingAudioWaveform.tsx
Closes #684 
Addresses the high CPU usage caused by Wavesurfer when rendering even small waveforms in the app header during think-aloud sessions.
This PR can possibly be extended to
- Accepting an audio stream (e.g., from screen recording or another component) as a prop.
- Storing waveform data during recording, reducing the need to repeatedly decode the entire audio/video file during analysis.
=> Custom audio waveform to improve performance

src/components/downloader/DownloadTidy.tsx
Closes #783
Fix MatrixResponse stored as [object Object] in tidy download
Before
After
No
=> Fix MatrixResponse stored as [object Object] in tidy download

src/components/downloader/DownloadTidy.tsx
Closes #685 
Add window event counts to the tidy download
=> Add event counts to tidy download

src/ResourceNotFound.tsx, src/components/interface/HelpModal.tsx, src/controllers/MarkdownController.tsx
Closes #570 
Don't trigger not found on false string. Instead, set a not found variable when the fetch fails.
Empty markdown
No
=> Fix md not found
